enum __DIALOG {
	TUTORIAL,
	BRIDGE_CONSOLE_START,
	ARMORY_GET_GUN,
	ARMORY_HAVE_GUN,
	ARMORY_REMINDER,
	ENGINE,
	AIRLOCK,
	LIGHT0,
	POWERSTATION_NOFUEL,
	POWERSTATION_FUELINHAND,
	POWERSTATION_HASFUEL,
	ELEVATOR_UP,
	FUEL_PICKUP,
	SIZE
}